[profile.dev]
codegen-units = 4

[workspace]
members = [
    "corr",
    "corrs",
    "corr-lib",
]
#[patch.crates-io]
#lexical-core = {git = 'https://github.com/Gelbpunkt/rust-lexical', branch = 'fix-warnings-and-update-deps'}